export const ROLE_CODES = {
  ADMIN: "ADMIN",
  ASSET_STAFF: "ASSET_STAFF",
  MANAGER: "MANAGER",
  END_USER: "END_USER",
};

export const MODULE_ACCESS = {
  DASHBOARD: [
    ROLE_CODES.ADMIN,
    ROLE_CODES.ASSET_STAFF,
    ROLE_CODES.MANAGER,
    ROLE_CODES.END_USER,
  ],
  CATALOG: [ROLE_CODES.ADMIN],
  ASSET: [ROLE_CODES.ADMIN, ROLE_CODES.ASSET_STAFF],
  ASSIGNMENT: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.MANAGER],
  INCIDENT: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.MANAGER, ROLE_CODES.END_USER],
  MAINTENANCE: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.MANAGER],
};

export const ACTION_ACCESS = {
  CATALOG_MANAGE: [ROLE_CODES.ADMIN],
  ASSET_MANAGE: [ROLE_CODES.ADMIN, ROLE_CODES.ASSET_STAFF],
  ASSIGNMENT_CREATE: [ROLE_CODES.ASSET_STAFF],
  ASSIGNMENT_APPROVE: [ROLE_CODES.MANAGER],
  ASSIGNMENT_COMPLETE: [ROLE_CODES.ASSET_STAFF],
  INCIDENT_REPORT: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.END_USER],
  INCIDENT_HANDLE: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.MANAGER],
  MAINTENANCE_MANAGE: [ROLE_CODES.ASSET_STAFF, ROLE_CODES.MANAGER],
};
