spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://roundhouse.proxy.rlwy.net:43406/railway}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:xPYlyrlpbNMMwNmSnLcwOWuSSVbeaDqV}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jackson.default-property-inclusion=non_null

server.address=0.0.0.0
server.port=${PORT:8080}
